/**
 * E2E tests for the ascent badge in list and grid mode.
 *
 * The list mode has always shown a tick badge (✓ or ✗) on climbs the
 * logged-in user has attempted at the currently-viewed angle. Grid mode
 * previously didn't show this. These tests verify that the badge renders
 * correctly in both modes.
 *
 * Requires the seeded dev database (vp run db:up). The test user
 * (test@boardsesh.com / test) has ~2000 Kilter ticks generated by the
 * social seed script — but they're distributed randomly across
 * ~10k climb/angle combinations, so a default list view (sorted by
 * ascents) is not guaranteed to include any climb the user has ticked
 * at the current angle. The `?showOnlyCompleted=true` filter restricts
 * the list to climbs the user has flashed or sent at this angle, which
 * pins the test against deterministic data without depending on the
 * random sampling distribution.
 *
 * See: https://github.com/boardsesh/boardsesh/issues/1559
 */
import { test, expect, type Page } from '@playwright/test';
import { loginAs } from './helpers/auth';

const BOARD_URL = '/kilter/original/12x12-square/screw_bolt/40/list';
const BOARD_URL_ONLY_COMPLETED = `${BOARD_URL}?showOnlyCompleted=true`;
const ASCENT_BADGE = '[data-testid="ascent-badge"]';
const CLIMB_CARD = '[data-testid="climb-card"]';

async function waitForClimbs(page: Page) {
  await page.waitForSelector(`${CLIMB_CARD}, #onboarding-climb-card`, { timeout: 30_000 });
}

test.describe('Grid mode — ascent badge', () => {
  test.setTimeout(90_000);

  test('ascent badge is visible in both list and grid mode', async ({ page }) => {
    // Log in to the base list URL first (loginAs uses an exact URL match for
    // its post-login wait, and query strings can be re-ordered by NextAuth's
    // callbackUrl validation), then navigate to the filtered URL.
    await loginAs(page, BOARD_URL);
    await waitForClimbs(page);
    await page.goto(BOARD_URL_ONLY_COMPLETED, { waitUntil: 'domcontentloaded' });
    await waitForClimbs(page);

    // showOnlyCompleted=true restricts the list to climbs the test user
    // has flashed or sent at the current angle, so every visible card
    // must render an ascent badge.
    const listBadges = page.locator(ASCENT_BADGE);
    await expect(listBadges.first()).toBeVisible({ timeout: 15_000 });
    expect(await listBadges.count()).toBeGreaterThan(0);

    // Switch to grid mode
    await page.getByRole('button', { name: 'Grid view' }).click();
    await expect(page.locator(CLIMB_CARD).first()).toBeVisible({ timeout: 15_000 });

    // Grid mode must also show badges
    const gridBadges = page.locator(CLIMB_CARD).locator(ASCENT_BADGE);
    await expect(gridBadges.first()).toBeVisible({ timeout: 15_000 });
    expect(await gridBadges.count()).toBeGreaterThan(0);
  });

  test('no ascent badge shown when logged out', async ({ page }) => {
    // Visit without logging in
    await page.goto(BOARD_URL, { waitUntil: 'domcontentloaded' });
    await waitForClimbs(page);

    // Unauthenticated cold loads can take a while to hydrate the virtualizer,
    // so switch to grid mode and wait generously for the first card to paint.
    const gridButton = page.getByRole('button', { name: 'Grid view' });
    await expect(gridButton).toBeVisible({ timeout: 10_000 });
    await gridButton.click();
    await expect(page.locator(CLIMB_CARD).first()).toBeVisible({ timeout: 30_000 });

    // No badges should appear when unauthenticated
    await expect(page.locator(CLIMB_CARD).locator(ASCENT_BADGE).first()).not.toBeVisible();
  });
});
